# Generated by Django 4.2.14 on 2024-07-20 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='rider_name',
        ),
        migrations.AddField(
            model_name='rides',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='rider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rider', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
