# Generated by Django 4.2.14 on 2024-07-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0002_remove_rides_driver_name_remove_rides_rider_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
