# Generated by Django 4.2.14 on 2024-07-22 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_rides_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
