# Generated by Django 4.2.14 on 2024-07-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_rides_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
