# Generated by Django 4.2.14 on 2024-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('DR', 'Driver'), ('UR', 'User'), ('AD', 'ADMIN')], default='UR', max_length=2),
        ),
    ]
